import { CountryConfiguration } from './types';
import { COUNTRY_TAX_SCHEMES } from './tax-compliance';

export const SUPPORTED_COUNTRIES: Record<string, CountryConfiguration> = {
  IN: {
    code: 'IN',
    name: 'India',
    callingCode: '+91',
    flagEmoji: '🇮🇳',
    defaultCurrency: 'INR',
    supportedCurrencies: ['INR', 'USD', 'GBP', 'EUR', 'AED', 'SAR'],
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'hi', 'ur', 'bn', 'ta', 'te', 'mr', 'gu', 'pa', 'kn', 'ml', 'or', 'as'],
    defaultTimezone: 'Asia/Kolkata',
    supportedTimezones: ['Asia/Kolkata'],
    numberingSystem: 'INDIAN_LAKH_CRORE',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '12h',
    decimalSeparator: '.',
    thousandSeparator: ',',
    preferredPaymentProviders: ['RAZORPAY', 'CASHFREE', 'STRIPE'],
    taxScheme: COUNTRY_TAX_SCHEMES.IN,
    foreignDonationRestricted: false,
    fcraReportingRequired: true,
  },
  GB: {
    code: 'GB',
    name: 'United Kingdom',
    callingCode: '+44',
    flagEmoji: '🇬🇧',
    defaultCurrency: 'GBP',
    supportedCurrencies: ['GBP', 'EUR', 'USD', 'INR'],
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ur', 'ar', 'bn', 'hi'],
    defaultTimezone: 'Europe/London',
    supportedTimezones: ['Europe/London'],
    numberingSystem: 'INTERNATIONAL_MILLION_BILLION',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    decimalSeparator: '.',
    thousandSeparator: ',',
    preferredPaymentProviders: ['STRIPE', 'PAYPAL'],
    taxScheme: COUNTRY_TAX_SCHEMES.GB,
    foreignDonationRestricted: false,
  },
  US: {
    code: 'US',
    name: 'United States',
    callingCode: '+1',
    flagEmoji: '🇺🇸',
    defaultCurrency: 'USD',
    supportedCurrencies: ['USD', 'CAD', 'GBP', 'EUR', 'INR'],
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'ur', 'hi'],
    defaultTimezone: 'America/New_York',
    supportedTimezones: [
      'America/New_York',
      'America/Chicago',
      'America/Denver',
      'America/Los_Angeles',
      'America/Anchorage',
      'Pacific/Honolulu',
    ],
    numberingSystem: 'INTERNATIONAL_MILLION_BILLION',
    dateFormat: 'MM/DD/YYYY',
    timeFormat: '12h',
    decimalSeparator: '.',
    thousandSeparator: ',',
    preferredPaymentProviders: ['STRIPE', 'PAYPAL'],
    taxScheme: COUNTRY_TAX_SCHEMES.US,
    foreignDonationRestricted: false,
  },
  AE: {
    code: 'AE',
    name: 'United Arab Emirates',
    callingCode: '+971',
    flagEmoji: '🇦🇪',
    defaultCurrency: 'AED',
    supportedCurrencies: ['AED', 'USD', 'SAR', 'EUR', 'INR', 'GBP'],
    defaultLanguage: 'ar',
    supportedLanguages: ['ar', 'en', 'ur', 'hi', 'fa'],
    defaultTimezone: 'Asia/Dubai',
    supportedTimezones: ['Asia/Dubai'],
    numberingSystem: 'INTERNATIONAL_MILLION_BILLION',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    decimalSeparator: '.',
    thousandSeparator: ',',
    preferredPaymentProviders: ['STRIPE'],
    taxScheme: COUNTRY_TAX_SCHEMES.AE,
    foreignDonationRestricted: false,
  },
  SA: {
    code: 'SA',
    name: 'Saudi Arabia',
    callingCode: '+966',
    flagEmoji: '🇸🇦',
    defaultCurrency: 'SAR',
    supportedCurrencies: ['SAR', 'AED', 'USD', 'EUR', 'INR'],
    defaultLanguage: 'ar',
    supportedLanguages: ['ar', 'en', 'ur'],
    defaultTimezone: 'Asia/Riyadh',
    supportedTimezones: ['Asia/Riyadh'],
    numberingSystem: 'INTERNATIONAL_MILLION_BILLION',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '24h',
    decimalSeparator: '.',
    thousandSeparator: ',',
    preferredPaymentProviders: ['STRIPE'],
    taxScheme: COUNTRY_TAX_SCHEMES.SA,
    foreignDonationRestricted: false,
  },
  CA: {
    code: 'CA',
    name: 'Canada',
    callingCode: '+1',
    flagEmoji: '🇨🇦',
    defaultCurrency: 'CAD',
    supportedCurrencies: ['CAD', 'USD', 'GBP', 'EUR', 'INR'],
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'fr', 'pa', 'ur', 'ar'],
    defaultTimezone: 'America/Toronto',
    supportedTimezones: ['America/Toronto', 'America/Vancouver', 'America/Edmonton'],
    numberingSystem: 'INTERNATIONAL_MILLION_BILLION',
    dateFormat: 'YYYY-MM-DD',
    timeFormat: '12h',
    decimalSeparator: '.',
    thousandSeparator: ',',
    preferredPaymentProviders: ['STRIPE', 'PAYPAL'],
    taxScheme: COUNTRY_TAX_SCHEMES.CA,
    foreignDonationRestricted: false,
  },
  AU: {
    code: 'AU',
    name: 'Australia',
    callingCode: '+61',
    flagEmoji: '🇦🇺',
    defaultCurrency: 'AUD',
    supportedCurrencies: ['AUD', 'USD', 'GBP', 'EUR', 'INR', 'AED'],
    defaultLanguage: 'en',
    supportedLanguages: ['en', 'ar', 'ur', 'hi'],
    defaultTimezone: 'Australia/Sydney',
    supportedTimezones: ['Australia/Sydney', 'Australia/Melbourne', 'Australia/Perth'],
    numberingSystem: 'INTERNATIONAL_MILLION_BILLION',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '12h',
    decimalSeparator: '.',
    thousandSeparator: ',',
    preferredPaymentProviders: ['STRIPE', 'PAYPAL'],
    taxScheme: COUNTRY_TAX_SCHEMES.AU,
    foreignDonationRestricted: false,
  },
  DE: {
    code: 'DE',
    name: 'Germany',
    callingCode: '+49',
    flagEmoji: '🇩🇪',
    defaultCurrency: 'EUR',
    supportedCurrencies: ['EUR', 'USD', 'GBP', 'INR'],
    defaultLanguage: 'de',
    supportedLanguages: ['de', 'en', 'ar', 'tr'],
    defaultTimezone: 'Europe/Berlin',
    supportedTimezones: ['Europe/Berlin'],
    numberingSystem: 'INTERNATIONAL_MILLION_BILLION',
    dateFormat: 'DD.MM.YYYY',
    timeFormat: '24h',
    decimalSeparator: ',',
    thousandSeparator: '.',
    preferredPaymentProviders: ['STRIPE', 'PAYPAL'],
    foreignDonationRestricted: false,
  },
  TR: {
    code: 'TR',
    name: 'Turkey',
    callingCode: '+90',
    flagEmoji: '🇹🇷',
    defaultCurrency: 'TRY',
    supportedCurrencies: ['TRY', 'USD', 'EUR', 'SAR'],
    defaultLanguage: 'tr',
    supportedLanguages: ['tr', 'ar', 'en'],
    defaultTimezone: 'Europe/Istanbul',
    supportedTimezones: ['Europe/Istanbul'],
    numberingSystem: 'INTERNATIONAL_MILLION_BILLION',
    dateFormat: 'DD.MM.YYYY',
    timeFormat: '24h',
    decimalSeparator: ',',
    thousandSeparator: '.',
    preferredPaymentProviders: ['STRIPE'],
    foreignDonationRestricted: false,
  },
  KE: {
    code: 'KE',
    name: 'Kenya',
    callingCode: '+254',
    flagEmoji: '🇰🇪',
    defaultCurrency: 'KES',
    supportedCurrencies: ['KES', 'USD', 'GBP', 'EUR', 'INR', 'AED'],
    defaultLanguage: 'sw',
    supportedLanguages: ['sw', 'en', 'ar', 'gu'],
    defaultTimezone: 'Africa/Nairobi',
    supportedTimezones: ['Africa/Nairobi'],
    numberingSystem: 'INTERNATIONAL_MILLION_BILLION',
    dateFormat: 'DD/MM/YYYY',
    timeFormat: '12h',
    decimalSeparator: '.',
    thousandSeparator: ',',
    preferredPaymentProviders: ['STRIPE'],
    foreignDonationRestricted: false,
  },
};

export class CountryRegistry {
  public static getAllCountries(): CountryConfiguration[] {
    return Object.values(SUPPORTED_COUNTRIES);
  }

  public static getCountry(code?: string): CountryConfiguration {
    if (!code) return SUPPORTED_COUNTRIES.IN;
    const normalized = code.toUpperCase();
    return SUPPORTED_COUNTRIES[normalized] || SUPPORTED_COUNTRIES.IN;
  }

  public static getSupportedCurrenciesForCountry(countryCode?: string): string[] {
    return this.getCountry(countryCode).supportedCurrencies;
  }

  public static getPreferredPaymentProvider(countryCode?: string, currency?: string): string {
    const country = this.getCountry(countryCode);
    if (currency && currency.toUpperCase() === 'INR') {
      return 'RAZORPAY';
    }
    return country.preferredPaymentProviders[0] || 'STRIPE';
  }
}
