import { prisma } from '@/lib/db';
import {
  ExpenseStatus,
  DonationStatus,
  GrantStatus,
  BudgetStatus,
  Prisma,
} from '@prisma/client';

export const AUDIT_DISCLAIMER_TEXT =
  'DISCLAIMER: This financial report is generated by the IMF-DOS Internal Accounting Engine for administrative and management information purposes. It does not constitute a certified statutory audit or formal tax certificate. All figures and statutory assumptions require verification and sign-off by a qualified Chartered Accountant / Statutory Auditor.';

export interface DateRangeFilter {
  startDate?: Date;
  endDate?: Date;
  fiscalYear?: number;
  projectId?: string;
}

export class FinancialReportService {
  /**
   * 1. Income & Expenditure Statement
   */
  public static async getIncomeAndExpenditureReport(filter: DateRangeFilter = {}) {
    const start = filter.startDate || new Date(new Date().getFullYear(), 0, 1);
    const end = filter.endDate || new Date();

    // 1. Incomes
    const donations = await prisma.donation.findMany({
      where: {
        paymentStatus: DonationStatus.SUCCESS,
        createdAt: { gte: start, lte: end },
      },
    });

    const grants = await prisma.grantAndCsrFunding.findMany({
      where: {
        createdAt: { gte: start, lte: end },
      },
    });

    // 2. Expenses
    const expenses = await prisma.expenseRecord.findMany({
      where: {
        status: ExpenseStatus.PAID,
        paymentDate: { gte: start, lte: end },
      },
    });

    const payrollPeriods = await prisma.payrollPeriod.findMany({
      where: {
        status: 'DISBURSED',
        startDate: { gte: start },
        endDate: { lte: end },
      },
      include: { payslips: true },
    });

    // Income Aggregations
    let totalDonations = 0;
    const donationsByFund: Record<string, number> = {};
    for (const d of donations) {
      const amt = Number(d.amountInINR);
      totalDonations += amt;
      donationsByFund[d.fundType] = (donationsByFund[d.fundType] || 0) + amt;
    }

    let totalInstitutionalGrants = 0;
    let totalCsrFunding = 0;
    for (const g of grants) {
      const amt = Number(g.disbursedAmountINR);
      if (g.grantType === 'CSR_CORPORATE') {
        totalCsrFunding += amt;
      } else {
        totalInstitutionalGrants += amt;
      }
    }

    const totalIncome = totalDonations + totalInstitutionalGrants + totalCsrFunding;

    // Expense Aggregations
    let totalProjectAidExpenses = 0;
    let totalFieldLogisticsExpenses = 0;
    let totalAdminOverheadExpenses = 0;
    let totalUtilitiesRentExpenses = 0;
    let totalLegalAuditExpenses = 0;
    let totalOtherExpenses = 0;

    for (const exp of expenses) {
      const amt = Number(exp.amount);
      switch (exp.category) {
        case 'PROJECT_EXECUTION':
        case 'RELIEF_AID_DIRECT':
          totalProjectAidExpenses += amt;
          break;
        case 'FIELD_LOGISTICS':
          totalFieldLogisticsExpenses += amt;
          break;
        case 'ADMINISTRATIVE_OVERHEAD':
          totalAdminOverheadExpenses += amt;
          break;
        case 'UTILITIES_RENT':
          totalUtilitiesRentExpenses += amt;
          break;
        case 'LEGAL_AND_AUDIT':
          totalLegalAuditExpenses += amt;
          break;
        default:
          totalOtherExpenses += amt;
          break;
      }
    }

    let totalPayrollSalaries = 0;
    let totalEmployerStatutory = 0;
    for (const period of payrollPeriods) {
      totalPayrollSalaries += Number(period.totalGrossAmountINR);
      for (const slip of period.payslips) {
        totalEmployerStatutory +=
          Number(slip.employerProvidentFund) + Number(slip.employerInsurance);
      }
    }

    const totalExpenditure =
      totalProjectAidExpenses +
      totalFieldLogisticsExpenses +
      totalAdminOverheadExpenses +
      totalUtilitiesRentExpenses +
      totalLegalAuditExpenses +
      totalOtherExpenses +
      totalPayrollSalaries +
      totalEmployerStatutory;

    const netSurplusOrDeficit = totalIncome - totalExpenditure;

    return {
      reportType: 'INCOME_AND_EXPENDITURE',
      period: { startDate: start, endDate: end },
      income: {
        donations: totalDonations,
        donationsByFund,
        institutionalGrants: totalInstitutionalGrants,
        csrFunding: totalCsrFunding,
        totalIncome,
      },
      expenditure: {
        directProjectAid: totalProjectAidExpenses,
        fieldLogistics: totalFieldLogisticsExpenses,
        staffSalariesGross: totalPayrollSalaries,
        employerStatutoryBenefits: totalEmployerStatutory,
        adminOverhead: totalAdminOverheadExpenses,
        utilitiesAndFacility: totalUtilitiesRentExpenses,
        legalAndAudit: totalLegalAuditExpenses,
        otherOperational: totalOtherExpenses,
        totalExpenditure,
      },
      netSurplusOrDeficit,
      surplusStatus: netSurplusOrDeficit >= 0 ? 'SURPLUS' : 'DEFICIT',
      disclaimer: AUDIT_DISCLAIMER_TEXT,
      generatedAt: new Date(),
    };
  }

  /**
   * 2. Receipts & Payments Account
   */
  public static async getReceiptsAndPaymentsReport(filter: DateRangeFilter = {}) {
    const start = filter.startDate || new Date(new Date().getFullYear(), 0, 1);
    const end = filter.endDate || new Date();

    // Opening balances: Asset accounts
    const bankHead = await prisma.accountHead.findUnique({
      where: { accountCode: '1010-HDFC-BANK-MAIN' },
    });
    const cashHead = await prisma.accountHead.findUnique({
      where: { accountCode: '1040-PETTY-CASH-IMPREST' },
    });

    // Inflows (Receipt vouchers)
    const receiptVouchers = await prisma.voucher.findMany({
      where: {
        voucherType: 'RECEIPT',
        voucherDate: { gte: start, lte: end },
      },
    });

    let totalReceipts = 0;
    for (const v of receiptVouchers) {
      totalReceipts += Number(v.totalAmount);
    }

    // Outflows (Payment vouchers)
    const paymentVouchers = await prisma.voucher.findMany({
      where: {
        voucherType: 'PAYMENT',
        voucherDate: { gte: start, lte: end },
      },
    });

    let totalPayments = 0;
    for (const v of paymentVouchers) {
      totalPayments += Number(v.totalAmount);
    }

    const currentBankBalance = Number(bankHead?.currentBalance || 0);
    const currentCashBalance = Number(cashHead?.currentBalance || 0);
    const closingBalance = currentBankBalance + currentCashBalance;
    const openingBalance = closingBalance - (totalReceipts - totalPayments);

    return {
      reportType: 'RECEIPTS_AND_PAYMENTS',
      period: { startDate: start, endDate: end },
      openingBalance: {
        bankAndCashEstimated: openingBalance,
      },
      receipts: {
        totalReceipts,
        count: receiptVouchers.length,
      },
      payments: {
        totalPayments,
        count: paymentVouchers.length,
      },
      closingBalance: {
        bankAccountBalance: currentBankBalance,
        cashImprestBalance: currentCashBalance,
        totalClosingBalance: closingBalance,
      },
      netCashFlow: totalReceipts - totalPayments,
      disclaimer: AUDIT_DISCLAIMER_TEXT,
      generatedAt: new Date(),
    };
  }

  /**
   * 3. Granular Expense Report
   */
  public static async getExpenseReport(filter: DateRangeFilter = {}) {
    const start = filter.startDate || new Date(new Date().getFullYear(), 0, 1);
    const end = filter.endDate || new Date();

    const expenses = await prisma.expenseRecord.findMany({
      where: {
        paymentDate: { gte: start, lte: end },
        ...(filter.projectId ? { projectId: filter.projectId } : {}),
      },
      include: {
        vendor: { select: { vendorCode: true, legalName: true, category: true } },
        project: { select: { projectNumber: true, title: true } },
      },
      orderBy: { paymentDate: 'desc' },
    });

    let totalAmount = 0;
    const byCategory: Record<string, number> = {};
    const byStatus: Record<string, number> = {};
    const byPaymentMethod: Record<string, number> = {};

    for (const exp of expenses) {
      const amt = Number(exp.amount);
      totalAmount += amt;
      byCategory[exp.category] = (byCategory[exp.category] || 0) + amt;
      byStatus[exp.status] = (byStatus[exp.status] || 0) + amt;
      byPaymentMethod[exp.paymentMethod] =
        (byPaymentMethod[exp.paymentMethod] || 0) + amt;
    }

    return {
      reportType: 'EXPENSE_REPORT',
      period: { startDate: start, endDate: end },
      summary: {
        totalExpensesCount: expenses.length,
        totalExpensesAmountINR: totalAmount,
        breakdownByCategory: byCategory,
        breakdownByStatus: byStatus,
        breakdownByPaymentMethod: byPaymentMethod,
      },
      expenses: expenses.map((e) => ({
        id: e.id,
        expenseNumber: e.expenseNumber,
        title: e.title,
        category: e.category,
        amount: Number(e.amount),
        paymentDate: e.paymentDate,
        paymentMethod: e.paymentMethod,
        paymentReference: e.paymentReference,
        vendor: e.vendor ? `${e.vendor.legalName} (${e.vendor.vendorCode})` : 'N/A',
        project: e.project ? `${e.project.title} (${e.project.projectNumber})` : 'N/A',
        status: e.status,
      })),
      disclaimer: AUDIT_DISCLAIMER_TEXT,
      generatedAt: new Date(),
    };
  }

  /**
   * 4. Budget vs Actual Comparison Report
   */
  public static async getBudgetVsActualReport(fiscalYear: number = 2026) {
    const budgets = await prisma.annualBudget.findMany({
      where: { fiscalYear },
      include: {
        lines: {
          include: {
            project: { select: { title: true, projectNumber: true } },
          },
        },
      },
    });

    const linesComparison = [];
    let totalAllocated = 0;
    let totalSpent = 0;

    for (const b of budgets) {
      for (const line of b.lines) {
        const allocated = Number(line.allocatedAmountINR);
        const spent = Number(line.spentAmountINR);
        const variance = allocated - spent;
        const variancePct = allocated > 0 ? ((allocated - spent) / allocated) * 100 : 0;
        const utilizationPct = allocated > 0 ? (spent / allocated) * 100 : 0;

        totalAllocated += allocated;
        totalSpent += spent;

        let status: 'HEALTHY' | 'WARNING_HIGH_UTILIZATION' | 'OVER_BUDGET' = 'HEALTHY';
        if (spent > allocated) {
          status = 'OVER_BUDGET';
        } else if (utilizationPct >= 80) {
          status = 'WARNING_HIGH_UTILIZATION';
        }

        linesComparison.push({
          lineCode: line.lineCode,
          title: line.title,
          category: line.category,
          project: line.project ? `${line.project.title} (${line.project.projectNumber})` : 'General / Central',
          allocatedAmountINR: allocated,
          spentAmountINR: spent,
          varianceINR: variance,
          variancePercent: Number(variancePct.toFixed(2)),
          utilizationPercent: Number(utilizationPct.toFixed(2)),
          status,
        });
      }
    }

    const overallVariance = totalAllocated - totalSpent;
    const overallUtilizationPct = totalAllocated > 0 ? (totalSpent / totalAllocated) * 100 : 0;

    return {
      reportType: 'BUDGET_VS_ACTUAL',
      fiscalYear,
      summary: {
        totalAllocatedINR: totalAllocated,
        totalSpentINR: totalSpent,
        varianceINR: overallVariance,
        overallUtilizationPercent: Number(overallUtilizationPct.toFixed(2)),
        status: totalSpent > totalAllocated ? 'OVER_BUDGET' : 'WITHIN_BUDGET',
      },
      lines: linesComparison,
      disclaimer: AUDIT_DISCLAIMER_TEXT,
      generatedAt: new Date(),
    };
  }

  /**
   * 5. Project Utilization Report
   */
  public static async getProjectUtilizationReport() {
    const projects = await prisma.project.findMany({
      include: {
        expenses: true,
        assistanceRecords: true,
        grants: true,
      },
      orderBy: { createdAt: 'desc' },
    });

    let grandTotalBudget = 0;
    let grandTotalDisbursed = 0;

    const projectReports = projects.map((p) => {
      const budget = Number(p.allocatedBudgetINR);
      const disbursed = Number(p.disbursedAmountINR);

      let directAidAmount = 0;
      for (const a of p.assistanceRecords) {
        directAidAmount += Number(a.amountINR || 0);
      }

      let operationalExpenses = 0;
      for (const exp of p.expenses) {
        operationalExpenses += Number(exp.amount);
      }

      const totalSpent = disbursed > 0 ? disbursed : directAidAmount + operationalExpenses;
      const remainingBalance = Math.max(0, budget - totalSpent);
      const utilizationRate = budget > 0 ? (totalSpent / budget) * 100 : 0;

      grandTotalBudget += budget;
      grandTotalDisbursed += totalSpent;

      return {
        id: p.id,
        projectNumber: p.projectNumber,
        title: p.title,
        category: p.category,
        stage: p.stage,
        targetBeneficiaries: p.targetBeneficiariesCount,
        actualBeneficiaries: p.actualBeneficiariesCount,
        allocatedBudgetINR: budget,
        directAidDisbursedINR: directAidAmount,
        operationalExpensesINR: operationalExpenses,
        totalSpentINR: totalSpent,
        remainingBalanceINR: remainingBalance,
        utilizationRatePercent: Number(utilizationRate.toFixed(2)),
        isOverBudget: totalSpent > budget,
      };
    });

    const overallRate = grandTotalBudget > 0 ? (grandTotalDisbursed / grandTotalBudget) * 100 : 0;

    return {
      reportType: 'PROJECT_UTILIZATION',
      summary: {
        totalProjectsCount: projects.length,
        grandTotalBudgetINR: grandTotalBudget,
        grandTotalSpentINR: grandTotalDisbursed,
        overallUtilizationPercent: Number(overallRate.toFixed(2)),
      },
      projects: projectReports,
      disclaimer: AUDIT_DISCLAIMER_TEXT,
      generatedAt: new Date(),
    };
  }

  /**
   * 6. Donation & Funding Stream Report
   */
  public static async getDonationReport(filter: DateRangeFilter = {}) {
    const start = filter.startDate || new Date(new Date().getFullYear(), 0, 1);
    const end = filter.endDate || new Date();

    const donations = await prisma.donation.findMany({
      where: {
        paymentStatus: DonationStatus.SUCCESS,
        createdAt: { gte: start, lte: end },
      },
      orderBy: { createdAt: 'desc' },
    });

    let totalAmount = 0;
    let totalTaxExempt80G = 0;
    let totalNon80G = 0;
    const byFund: Record<string, { count: number; totalINR: number }> = {};
    const byProvider: Record<string, { count: number; totalINR: number }> = {};
    const byTicketSize: Record<string, { count: number; totalINR: number }> = {
      'Micro (< ₹1,000)': { count: 0, totalINR: 0 },
      'Standard (₹1,000 - ₹9,999)': { count: 0, totalINR: 0 },
      'Major (₹10,000 - ₹49,999)': { count: 0, totalINR: 0 },
      'Patron (≥ ₹50,000)': { count: 0, totalINR: 0 },
    };

    for (const d of donations) {
      const amt = Number(d.amountInINR);
      totalAmount += amt;

      if (d.is80GRequested || d.is80GIssued) {
        totalTaxExempt80G += amt;
      } else {
        totalNon80G += amt;
      }

      // Fund breakdown
      if (!byFund[d.fundType]) byFund[d.fundType] = { count: 0, totalINR: 0 };
      byFund[d.fundType].count++;
      byFund[d.fundType].totalINR += amt;

      // Provider breakdown
      if (!byProvider[d.paymentProvider])
        byProvider[d.paymentProvider] = { count: 0, totalINR: 0 };
      byProvider[d.paymentProvider].count++;
      byProvider[d.paymentProvider].totalINR += amt;

      // Ticket size
      if (amt < 1000) {
        byTicketSize['Micro (< ₹1,000)'].count++;
        byTicketSize['Micro (< ₹1,000)'].totalINR += amt;
      } else if (amt < 10000) {
        byTicketSize['Standard (₹1,000 - ₹9,999)'].count++;
        byTicketSize['Standard (₹1,000 - ₹9,999)'].totalINR += amt;
      } else if (amt < 50000) {
        byTicketSize['Major (₹10,000 - ₹49,999)'].count++;
        byTicketSize['Major (₹10,000 - ₹49,999)'].totalINR += amt;
      } else {
        byTicketSize['Patron (≥ ₹50,000)'].count++;
        byTicketSize['Patron (≥ ₹50,000)'].totalINR += amt;
      }
    }

    const averageDonation = donations.length > 0 ? totalAmount / donations.length : 0;

    return {
      reportType: 'DONATION_REPORT',
      period: { startDate: start, endDate: end },
      summary: {
        totalDonationsCount: donations.length,
        totalAmountINR: totalAmount,
        averageDonationINR: Number(averageDonation.toFixed(2)),
        total80GTaxExemptINR: totalTaxExempt80G,
        totalNonExemptINR: totalNon80G,
        percent80G: totalAmount > 0 ? Number(((totalTaxExempt80G / totalAmount) * 100).toFixed(2)) : 0,
      },
      breakdownByFund: byFund,
      breakdownByPaymentProvider: byProvider,
      breakdownByTicketSize: byTicketSize,
      disclaimer: AUDIT_DISCLAIMER_TEXT,
      generatedAt: new Date(),
    };
  }

  /**
   * 7. Monthly Comprehensive Financial Report
   */
  public static async getMonthlyReport(year: number = new Date().getFullYear()) {
    const months = [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December',
    ];

    const monthlyData = [];
    let yearTotalIncome = 0;
    let yearTotalExpense = 0;

    for (let m = 0; m < 12; m++) {
      const start = new Date(year, m, 1);
      const end = new Date(year, m + 1, 0, 23, 59, 59, 999);

      const donations = await prisma.donation.aggregate({
        where: {
          paymentStatus: DonationStatus.SUCCESS,
          createdAt: { gte: start, lte: end },
        },
        _sum: { amountInINR: true },
        _count: { id: true },
      });

      const expenses = await prisma.expenseRecord.aggregate({
        where: {
          status: ExpenseStatus.PAID,
          paymentDate: { gte: start, lte: end },
        },
        _sum: { amount: true },
        _count: { id: true },
      });

      const payroll = await prisma.payrollPeriod.aggregate({
        where: {
          year,
          month: m + 1,
          status: 'DISBURSED',
        },
        _sum: { totalGrossAmountINR: true },
      });

      const income = Number(donations._sum.amountInINR || 0);
      const expense =
        Number(expenses._sum.amount || 0) +
        Number(payroll._sum.totalGrossAmountINR || 0);
      const net = income - expense;

      yearTotalIncome += income;
      yearTotalExpense += expense;

      monthlyData.push({
        monthNumber: m + 1,
        monthName: months[m],
        totalIncomeINR: income,
        totalDonationsCount: donations._count.id,
        totalExpensesINR: expense,
        totalExpenseCount: expenses._count.id,
        netSurplusDeficitINR: net,
      });
    }

    return {
      reportType: 'MONTHLY_REPORT',
      year,
      summary: {
        annualTotalIncomeINR: yearTotalIncome,
        annualTotalExpenseINR: yearTotalExpense,
        annualNetSurplusDeficitINR: yearTotalIncome - yearTotalExpense,
      },
      months: monthlyData,
      disclaimer: AUDIT_DISCLAIMER_TEXT,
      generatedAt: new Date(),
    };
  }

  /**
   * 8. Annual Financial Report & 85% Statutory Accumulation Tracker
   */
  public static async getAnnualReport(fiscalYear: number = new Date().getFullYear()) {
    const start = new Date(fiscalYear, 0, 1);
    const end = new Date(fiscalYear, 11, 31, 23, 59, 59, 999);

    const [incomeExp, ledgerSummary, grants] = await Promise.all([
      FinancialReportService.getIncomeAndExpenditureReport({ startDate: start, endDate: end }),
      prisma.accountHead.findMany(),
      prisma.grantAndCsrFunding.findMany({ where: { createdAt: { gte: start, lte: end } } }),
    ]);

    const totalIncome = incomeExp.income.totalIncome;
    const totalAppliedToCharity = incomeExp.expenditure.directProjectAid + incomeExp.expenditure.fieldLogistics;
    const totalAppliedOverall = incomeExp.expenditure.totalExpenditure;

    // Simulation of 85% Statutory Non-Profit Utilization
    const minRequiredApplication85Pct = totalIncome * 0.85;
    const shortfallOrExcess = totalAppliedOverall - minRequiredApplication85Pct;
    const actualApplicationPct = totalIncome > 0 ? (totalAppliedOverall / totalIncome) * 100 : 0;
    const is85PctSatisfied = totalAppliedOverall >= minRequiredApplication85Pct;

    let totalRestrictedReserves = 0;
    let totalGeneralReserves = 0;
    let totalAssetValue = 0;

    for (const h of ledgerSummary) {
      const bal = Number(h.currentBalance);
      if (h.isRestricted) totalRestrictedReserves += bal;
      if (h.accountType === 'EQUITY_RESERVE' && !h.isRestricted) totalGeneralReserves += bal;
      if (h.accountType === 'ASSET') totalAssetValue += bal;
    }

    return {
      reportType: 'ANNUAL_REPORT',
      fiscalYear,
      financialSummary: {
        totalRevenueINR: totalIncome,
        totalExpenditureINR: totalAppliedOverall,
        netSurplusINR: incomeExp.netSurplusOrDeficit,
        totalAssetsINR: totalAssetValue,
        restrictedReservesINR: totalRestrictedReserves,
        generalReservesINR: totalGeneralReserves,
      },
      statutory85PercentRuleAnalysis: {
        ruleName: 'Charitable Income Application Target (85% Standard NGO Model)',
        minimumRequiredApplicationINR: Number(minRequiredApplication85Pct.toFixed(2)),
        actualApplicationAchievedINR: totalAppliedOverall,
        applicationPercentage: Number(actualApplicationPct.toFixed(2)),
        isStatutoryTargetSatisfied: is85PctSatisfied,
        shortfallOrSurplusApplicationINR: Number(shortfallOrExcess.toFixed(2)),
        reviewRequirement: 'REQUIRES PROFESSIONAL CA VERIFICATION FOR FORM 10 / ACCUMULATION FILING',
      },
      activeGrantsCount: grants.length,
      disclaimer: AUDIT_DISCLAIMER_TEXT,
      generatedAt: new Date(),
    };
  }

  /**
   * Helper: Exports report data into CSV format
   */
  public static exportToCsv(reportType: string, data: any): string {
    const lines: string[] = [];

    // Header Disclaimer
    lines.push(`"--- IMF-DOS FINANCIAL AUDIT EXPORT ---"`);
    lines.push(`"Report Type: ${reportType}"`);
    lines.push(`"Generated At: ${new Date().toISOString()}"`);
    lines.push(`"DISCLAIMER: ${AUDIT_DISCLAIMER_TEXT}"`);
    lines.push('');

    switch (reportType) {
      case 'INCOME_AND_EXPENDITURE': {
        lines.push('"Category","Component","Amount (INR)"');
        lines.push(`"Income","General Donations",${data.income.donations}`);
        lines.push(`"Income","Institutional Grants",${data.income.institutionalGrants}`);
        lines.push(`"Income","CSR Corporate Funding",${data.income.csrFunding}`);
        lines.push(`"Income","TOTAL REVENUE",${data.income.totalIncome}`);
        lines.push('');
        lines.push(`"Expenditure","Direct Project Relief & Aid",${data.expenditure.directProjectAid}`);
        lines.push(`"Expenditure","Field Operations Logistics",${data.expenditure.fieldLogistics}`);
        lines.push(`"Expenditure","Staff Salaries & Wages",${data.expenditure.staffSalariesGross}`);
        lines.push(`"Expenditure","Employer Statutory Benefits",${data.expenditure.employerStatutoryBenefits}`);
        lines.push(`"Expenditure","Administrative Overhead",${data.expenditure.adminOverhead}`);
        lines.push(`"Expenditure","Utilities & Rent",${data.expenditure.utilitiesAndFacility}`);
        lines.push(`"Expenditure","Legal & Audit Fees",${data.expenditure.legalAndAudit}`);
        lines.push(`"Expenditure","TOTAL EXPENDITURE",${data.expenditure.totalExpenditure}`);
        lines.push('');
        lines.push(`"Summary","NET SURPLUS / (DEFICIT)",${data.netSurplusOrDeficit}`);
        break;
      }
      case 'BUDGET_VS_ACTUAL': {
        lines.push('"Line Code","Title","Category","Project","Allocated (INR)","Spent (INR)","Variance (INR)","Utilization %","Status"');
        for (const l of data.lines || []) {
          lines.push(
            `"${l.lineCode}","${l.title}","${l.category}","${l.project}",${l.allocatedAmountINR},${l.spentAmountINR},${l.varianceINR},${l.utilizationPercent},"${l.status}"`
          );
        }
        break;
      }
      case 'PROJECT_UTILIZATION': {
        lines.push('"Project Number","Title","Category","Stage","Budget (INR)","Direct Aid (INR)","Operations (INR)","Total Spent (INR)","Remaining (INR)","Utilization %"');
        for (const p of data.projects || []) {
          lines.push(
            `"${p.projectNumber}","${p.title}","${p.category}","${p.stage}",${p.allocatedBudgetINR},${p.directAidDisbursedINR},${p.operationalExpensesINR},${p.totalSpentINR},${p.remainingBalanceINR},${p.utilizationRatePercent}`
          );
        }
        break;
      }
      case 'EXPENSE_REPORT': {
        lines.push('"Expense Number","Title","Category","Amount (INR)","Date","Payment Method","Vendor","Project","Status"');
        for (const e of data.expenses || []) {
          lines.push(
            `"${e.expenseNumber}","${e.title}","${e.category}",${e.amount},"${e.paymentDate}","${e.paymentMethod}","${e.vendor}","${e.project}","${e.status}"`
          );
        }
        break;
      }
      default: {
        lines.push('"Key","Value"');
        for (const [k, v] of Object.entries(data.summary || data)) {
          lines.push(`"${k}","${typeof v === 'object' ? JSON.stringify(v) : v}"`);
        }
        break;
      }
    }

    return lines.join('\n');
  }
}
