import { BaseAiProvider } from './base-provider';
import { AiModelConfig, AiPromptContext } from '../types';

export class AnthropicAiProvider extends BaseAiProvider {
  readonly name = 'ANTHROPIC';
  readonly defaultModel = 'claude-3-5-sonnet-20241022';
  readonly availableModels = [
    'claude-3-5-sonnet-20241022',
    'claude-3-5-haiku-20241022',
    'claude-3-opus-20240229',
  ];

  private apiKey: string | null;

  constructor(apiKey?: string) {
    super();
    this.apiKey = apiKey || process.env.ANTHROPIC_API_KEY || null;
  }

  isConfigured(): boolean {
    return !!this.apiKey;
  }

  async generateContent(
    sanitizedPrompt: string,
    context: AiPromptContext,
    config?: Partial<AiModelConfig>
  ): Promise<{
    text: string;
    tokensPrompt: number;
    tokensCompletion: number;
    modelUsed: string;
  }> {
    const modelUsed = config?.modelName || this.defaultModel;

    if (!this.apiKey) {
      throw new Error(
        'Anthropic API key is not configured. Please set ANTHROPIC_API_KEY environment variable or choose another provider.'
      );
    }

    const systemPrompt = `You are the AI Assistant for Imam E Mahdi Foundation (IMF), an Indian Non-Profit NGO operating with high standards of Sharia compliance, financial transparency, and humanitarian dignity.
Task: ${context.taskType}
Tone: ${context.tone || 'FORMAL'}
Target Language: ${context.targetLanguage || 'en'}
Target Audience: ${context.targetAudience || 'General Public & Donors'}

CRITICAL SAFETY DIRECTIVE:
You must NOT finalize or issue binding legal advice, formal tax certificates, statutory audit conclusions, or government regulatory approvals. Always format outputs with appropriate disclaimers where relevant.`;

    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': this.apiKey,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify({
        model: modelUsed,
        max_tokens: config?.maxTokens ?? 2048,
        temperature: config?.temperature ?? 0.7,
        system: systemPrompt,
        messages: [
          { role: 'user', content: `Title: ${context.title}\n\nPrompt:\n${sanitizedPrompt}` },
        ],
      }),
    });

    if (!response.ok) {
      const err = await response.text();
      throw new Error(`Anthropic API Error [${response.status}]: ${err}`);
    }

    const data = await response.json();
    const text = data.content?.[0]?.text || 'No output generated by Anthropic Claude.';
    const tokensPrompt = data.usage?.input_tokens || this.estimateTokenCount(sanitizedPrompt);
    const tokensCompletion = data.usage?.output_tokens || this.estimateTokenCount(text);

    return {
      text,
      tokensPrompt,
      tokensCompletion,
      modelUsed,
    };
  }
}
