import { BaseAiProvider } from './base-provider';
import { AiModelConfig, AiPromptContext } from '../types';

export class GeminiAiProvider extends BaseAiProvider {
  readonly name = 'GEMINI';
  readonly defaultModel = 'gemini-1.5-flash';
  readonly availableModels = ['gemini-1.5-flash', 'gemini-1.5-pro', 'gemini-2.0-flash'];

  private apiKey: string | null;

  constructor(apiKey?: string) {
    super();
    this.apiKey = apiKey || process.env.GEMINI_API_KEY || process.env.GOOGLE_AI_API_KEY || null;
  }

  isConfigured(): boolean {
    return !!this.apiKey;
  }

  async generateContent(
    sanitizedPrompt: string,
    context: AiPromptContext,
    config?: Partial<AiModelConfig>
  ): Promise<{
    text: string;
    tokensPrompt: number;
    tokensCompletion: number;
    modelUsed: string;
  }> {
    const modelUsed = config?.modelName || this.defaultModel;

    if (!this.apiKey) {
      throw new Error(
        'Gemini API key is not configured. Please set GEMINI_API_KEY environment variable or choose the MOCK provider.'
      );
    }

    const systemInstruction = `You are the AI Assistant for Imam E Mahdi Foundation (IMF), an Indian Non-Profit NGO operating with high standards of Sharia compliance, financial transparency, and humanitarian dignity.
Task: ${context.taskType}
Tone: ${context.tone || 'FORMAL'}
Target Language: ${context.targetLanguage || 'en'}
Target Audience: ${context.targetAudience || 'General Public & Donors'}

CRITICAL SAFETY DIRECTIVE:
You must NOT finalize or issue binding legal advice, formal tax certificates, statutory audit conclusions, or government regulatory approvals. Always format outputs with appropriate disclaimers where relevant.`;

    const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelUsed}:generateContent?key=${this.apiKey}`;

    const body = {
      contents: [
        {
          role: 'user',
          parts: [
            {
              text: `${systemInstruction}\n\nTitle: ${context.title}\n\nPrompt/Input:\n${sanitizedPrompt}`,
            },
          ],
        },
      ],
      generationConfig: {
        temperature: config?.temperature ?? 0.7,
        maxOutputTokens: config?.maxTokens ?? 2048,
      },
    };

    const startTime = Date.now();
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(body),
    });

    if (!response.ok) {
      const errText = await response.text();
      throw new Error(`Gemini API Error [${response.status}]: ${errText}`);
    }

    const data = await response.json();
    const text =
      data.candidates?.[0]?.content?.parts?.[0]?.text ||
      'No content generated by Gemini provider.';

    const tokensPrompt =
      data.usageMetadata?.promptTokenCount || this.estimateTokenCount(sanitizedPrompt);
    const tokensCompletion =
      data.usageMetadata?.candidatesTokenCount || this.estimateTokenCount(text);

    return {
      text,
      tokensPrompt,
      tokensCompletion,
      modelUsed,
    };
  }
}
