import { BaseAiProvider } from './base-provider';
import { AiModelConfig, AiPromptContext } from '../types';

export class OpenAiProvider extends BaseAiProvider {
  readonly name = 'OPENAI';
  readonly defaultModel = 'gpt-4o-mini';
  readonly availableModels = ['gpt-4o-mini', 'gpt-4o', 'gpt-3.5-turbo'];

  private apiKey: string | null;

  constructor(apiKey?: string) {
    super();
    this.apiKey = apiKey || process.env.OPENAI_API_KEY || null;
  }

  isConfigured(): boolean {
    return !!this.apiKey;
  }

  async generateContent(
    sanitizedPrompt: string,
    context: AiPromptContext,
    config?: Partial<AiModelConfig>
  ): Promise<{
    text: string;
    tokensPrompt: number;
    tokensCompletion: number;
    modelUsed: string;
  }> {
    const modelUsed = config?.modelName || this.defaultModel;

    if (!this.apiKey) {
      throw new Error(
        'OpenAI API key is not configured. Please set OPENAI_API_KEY environment variable or choose another provider.'
      );
    }

    const systemPrompt = `You are the AI Assistant for Imam E Mahdi Foundation (IMF), an Indian Non-Profit NGO operating with high standards of Sharia compliance, financial transparency, and humanitarian dignity.
Task: ${context.taskType}
Tone: ${context.tone || 'FORMAL'}
Target Language: ${context.targetLanguage || 'en'}
Target Audience: ${context.targetAudience || 'General Public & Donors'}

CRITICAL SAFETY DIRECTIVE:
You must NOT finalize or issue binding legal advice, formal tax certificates, statutory audit conclusions, or government regulatory approvals. Always format outputs with appropriate disclaimers where relevant.`;

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${this.apiKey}`,
      },
      body: JSON.stringify({
        model: modelUsed,
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: `Title: ${context.title}\n\nPrompt:\n${sanitizedPrompt}` },
        ],
        temperature: config?.temperature ?? 0.7,
        max_tokens: config?.maxTokens ?? 2048,
      }),
    });

    if (!response.ok) {
      const err = await response.text();
      throw new Error(`OpenAI API Error [${response.status}]: ${err}`);
    }

    const data = await response.json();
    const text = data.choices?.[0]?.message?.content || 'No output generated by OpenAI.';
    const tokensPrompt = data.usage?.prompt_tokens || this.estimateTokenCount(sanitizedPrompt);
    const tokensCompletion = data.usage?.completion_tokens || this.estimateTokenCount(text);

    return {
      text,
      tokensPrompt,
      tokensCompletion,
      modelUsed,
    };
  }
}
